version: "3"
services:
  web:
    image: kebes/nodeapp:v1
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:3000"
    networks:
      - webnet
networks:
  webnet: