FROM node:8-alpine

RUN mkdir -p /app
WORKDIR /app

COPY package.json /app/
COPY package-lock.json /app/
RUN npm install

COPY . /app

ENV PORT 3000

EXPOSE 3000
EXPOSE 5858
CMD [ "node", "--inspect=0.0.0.0:5858", "src/sender.js" ]